CREATE TABLE [dbo].[PARTICIPANTES]
(
	[Id] BIGINT NOT NULL PRIMARY KEY, 
    [REG] CHAR(4) NOT NULL DEFAULT 0150, 
    [COD_PART] VARCHAR(60) NOT NULL, 
    [NOME] VARCHAR(100) NOT NULL, 
    [COD_PAIS] SMALLINT NOT NULL, 
    [CNPJ] CHAR(14) NULL, 
    [CPF] CHAR(11) NULL, 
    [IE] VARCHAR(14) NULL, 
    [COD_MUN] CHAR(7) NULL, 
    [SUFRAMA] CHAR(9) NULL, 
    [END] VARCHAR(60) NOT NULL, 
    [NUM] VARCHAR(10) NULL, 
    [COMPL] VARCHAR(60) NULL, 
    [BAIRRO] VARCHAR(60) NULL 
)
